### PR TITLE
fix bad Future code generated for java primitive return values

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
dont generate things like Future<int>
note, however, that this brings up an issue with primitive/immutable return types - we're forced to expose the underlying XdrAble wrapper - so we noe generate methods that return Future<XdrLong> instead of Future<Long>.

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
ok to test.

**Comment by radai-rosenblatt** [comment]
if there a link to the failed run page somewhere? mvn clean install passed locally for me

**Comment by kofemann** [comment]
check here https://ci.dcache.org/job/oncrpc4j-pull-requests/3/testReport/

**Comment by radai-rosenblatt** [comment]
ok, should be fixed now

**Comment by kofemann** [comment]
ok to test

**Pull request merged**
