### PR TITLE
bugfixes and enhancements to large const definitions

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
1. fixed a bug where "0" was treated as octal (oops)
2. allow specifying consts beyond max signed int/long as hex/octal

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
some how our build system does not updates here....


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project oncrpc4j-rpcgen: Compilation failure: Compilation failure:
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:[26,33] error: cannot find symbol
[ERROR] 
[ERROR] could not parse error message:   symbol:   method compareUnsigned(int,int)
[ERROR] location: class Integer
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:27: error: cannot find symbol
[ERROR] Assert.assertTrue(Integer.compareUnsigned(maxInt, Calculator.UNSIGNED_INT_HEX_CONST) == 0);
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   method compareUnsigned(int,int)
[ERROR] location: class Integer
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:28: error: cannot find symbol
[ERROR] Assert.assertTrue(Integer.compareUnsigned(maxInt, (int) Calculator.UNSIGNED_INT_DEC_CONST) == 0);
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   method compareUnsigned(int,int)
[ERROR] location: class Integer
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:29: error: cannot find symbol
[ERROR] Assert.assertTrue(Long.compareUnsigned(maxLong, Calculator.UNSIGNED_LONG_OCT_CONST) == 0);
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   method compareUnsigned(long,long)
[ERROR] location: class Long
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:30: error: cannot find symbol
[ERROR] Assert.assertTrue(Long.compareUnsigned(maxLong, Calculator.UNSIGNED_LONG_HEX_CONST) == 0);
[ERROR] ^
[ERROR] 
[ERROR] could not parse error message:   symbol:   method compareUnsigned(long,long)
[ERROR] location: class Long
[ERROR] /scratch/jenkins/jenkins/workspace/oncrpc4j-pull-requests/oncrpc4j-rpcgen/src/test/java/org/dcache/oncrpc4j/rpcgen/BigConstsGenerationTest.java:31: error: cannot find symbol
[ERROR] Assert.assertTrue(Long.compareUnsigned(maxLong, Calculator.UNSIGNED_LONG_DEC_CONST.longValue()) == 0);
[ERROR] ^
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :oncrpc4j-rpcgen

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
retest this please

**Comment by radai-rosenblatt** [comment]
I think I might have used jdk8 methods in the test code.
Will fix

**Comment by kofemann** [comment]
If jdk8 is OK for you in production, I can update pom to enforce it during
build and tests.

**Comment by radai-rosenblatt** [comment]
I've modified the code to use jdk7 methods for comparing unsigned ints and longs.
we indeed use java8 in production, but the min supported jdk level for dcache is your call, and really shouldnt change just for test code.

and now jrpcgen has better constant support than the C rpcgen :-)

**Comment by kofemann** [comment]
thanks!

**Comment by kofemann** [comment]
dCache\s main code is java8. Oncrpc4j is the only java7 code we have due to
external usage :). I will change it for master. Existing branches will stay
with java7.

-kofemann
/** caffeinated mutations of the core personality */

**Comment by kofemann** [comment]
retest this please

**Pull request merged**
