### PR TITLE
Used a concurrent hashmap for reply queue for improved performance - …

### PR DESCRIPTION
**Pull request by amahapat**
…using a hash map required locking at the haspmap level for updates.

Signed-off-by: Akshaya Mahapatra <akshaya.mahapatra@primarydata.com>

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test.

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
Thanks! BTW, we are working on issue #9 right now. As a result, this part will be re-done.

**Comment by amahapat** [comment]
Thank you.

**Pull request merged**
