### PR TITLE
add a test case to demonstrate #31 and a proposed solution

### PR DESCRIPTION
**Pull request by radai-rosenblatt**

### CODE REVIEW

**Comment by kofemann** [comment]
Hi Radai, 

could you please add Signed-off-by line?

( git commit -s )

**Comment by radai-rosenblatt** [comment]
signed-off added

**Comment by radai-rosenblatt** [comment]
I've changed the code to start Xdr objects with a 1K buffer. test now passes.

**Comment by kofemann** [comment]
thanks

**Pull request merged**
