### PR TITLE
Set leader-follower strategy in grizzly if selected in oncrpc4j.

### PR DESCRIPTION
**Pull request by jcalcote**
By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by jcalcote** [comment]
This is in reference to issue https://github.com/dCache/oncrpc4j/issues/97

**Comment by jcalcote** [comment]
It would be nice if this patch could also be backported to the 3.1 branch for those java 8 users still out there (like me) :)

**Comment by kofemann** [comment]
Thanks!

**Comment by kofemann** [comment]
crap. Just noticed, that packages was never built and published! Fixed now.

**Pull request merged**
