### PR TITLE
Added input for service name while creating OncRpcClients. 

### PR DESCRIPTION
**Pull request by amahapat**
This make it easy to identify threads created on behalf of a client.

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
Thanks for PR. Please fix following:
  - make pull request against master branch
  - use 'git commit -s' or 'git commit --ammend -s' to add Signed-of-by:

**Comment by amahapat** [comment]
Made the commit for master branch. Also added Signed-of-by as you suggested. However I need it on 2.6 release as that is what we use at this time.

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
I will backport it to 2.6

**Comment by amahapat** [comment]
Thank you.

**Comment by amahapat** [comment]
Also would you please create a tag for 2.6.3 so that we don't inadvertently
pull some other change made to 2.6.0 snapshot?

thanks
Akshaya

**Comment by kofemann** [comment]
2.6.3 is released.

**Comment by amahapat** [comment]
Thank you.

**Pull request merged**
